/**
 */
package org.gemoc.xcapella.dataflow.xdsml.dataflowmt.fa;

import org.gemoc.xcapella.dataflow.xdsml.dataflowmt.capellacore.Allocation;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Functional Chain Realization</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.gemoc.xcapella.dataflow.xdsml.dataflowmt.fa.FaPackage#getFunctionalChainRealization()
 * @model annotation="http://www.polarsys.org/kitalpha/ecore/documentation description='an allocation link between two Functional Chains' usage\040guideline='this link is typically generated by the Capella tool during automated transitions between design levels' used\040in\040levels='operational,system,logical,physical' usage\040examples='n/a' constraints='none' comment/notes='none' reference\040documentation='none'"
 *        annotation="http://www.polarsys.org/capella/MNoE/CapellaLike/Mapping UML/SysML\040semantic\040equivalences='' base\040metaclass\040in\040UML/SysML\040profile\040='uml::Realization' explanation='none' constraints='none'"
 * @generated
 */
public interface FunctionalChainRealization extends Allocation {
} // FunctionalChainRealization
